### PR TITLE
TEST: test batch file, arithmetic, abs and integer variable test

### LINKED ISSUE #17: test +, -, *, /, || integer variable
- [x] a batch file to execute all test
- [x] addition
- [x] subtraction
- [x] multiplication
- [x] divison
- [x] absolute value
- [x] parenthesis
- [x] store and print integer variables

### PR DESCRIPTION
**Pull request by Argentum11**
## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [x] **Testing**
- [ ] **Other (please describe)**

## Description
1. Add test case written in python for addition, subtraction, multiplication, divison, absolute value, parenthesis, store and print integer variables and a batch file that executes pytest. 
2. Then pytest goes on to reach for python files in "test_*.py" or "*_test.py" format, executing all test functions  
3. All test results will be display in console and stored in report.md so that further PR viewers can see if the PR submitter checks his/her on PR ( test date and time will also be added in report.md after testing)

## Expected behavior
**Screenshots**
image

## Related Issue
close #17

### CODE REVIEW

**Comment by 0-ch** [comment]
我安裝完兩個套件後 跑test.bat 出現不一樣的畫面
螢幕擷取畫面 2023-04-20 224915

**Review by 0-ch — APPROVED** [review]
OK

**Comment by 0-ch** [comment]
@Argentum11 要直接刪掉分支嗎

**Comment by Argentum11** [comment]
> @Argentum11 要直接刪掉分支嗎

要，之後merge完都直接把branch刪掉

**Pull request merged**
