### PR TITLE
cout string(include \t\n\0\\ and quotation marks)

### LINKED ISSUE #21: string
output string through cout

### PR DESCRIPTION
**Pull request by 0-ch**
## Types of changes
- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Testing**
- [ ] **Other (please describe)**

## Description
新增cout字串功能 包括\t \n \0 \\\\ \\\"  \\\'

## Expected behavior
|command name|command example|command output|
|-|-|-|
|output string|cout<<"adc"<<endl;|adc\n|
|output \t |cout<<"\tadc"<<endl;|\tadc\n|
|output \n|cout<<"ad\nc"<<endl;|ad\nc|
|output \0 (end of string) |cout<<"ad\0c"<<endl;|ab\0\n|
|output \ |cout<<"\\\\"<<endl;|\\\\n|
|output " |cout<<"\\""<<endl;|"\n|
|output ' |cout<<"\\'"<<endl;|'\n|

## Related Issue
close #21

### CODE REVIEW

**Comment by 0-ch** [comment]
等下 好像有問題 輸入兩行會出錯

**Comment by 0-ch** [comment]
修正好了 把\n \t加回去了

**Review by Argentum11 — CHANGES_REQUESTED** [review]
@0-ch 
It seems that all the existing functionality don't work, is there a manual about how to use all the existing functionality ?

1. Variable assignment doesn't work on second variable
image
image
image

2. print variables don't work
image
image
image

3. All test failed on my computer (the result is as followed), could you please test again ?
image

4. This are the conflicting result in bison, please use
```bash
bison -d -v CFE.y
```
and open CFE.output (using big 5 encoding) to see details
image

**Comment by 0-ch** [comment]
> @0-ch 好像所有現有功能都不能起作用，是否有關於如何使用所有現有功能的手冊？
> 
> 1. 變量賦值不適合用於第二個變量
>    圖片
>    圖片
>    圖片
> 2. 打印量不起作用
>    圖片
>    圖片
>    圖片
> 3. 在我的電腦上全部測試失敗（結果如下），請你測試一次再下好嗎？
>    圖片
> 4. 這是野牛的衝突結果，請使用
> 
> ```shell
> bison -d -v CFE.y
> ```
> 
> 並打開CFE.output（使用big 5編碼）查看詳細信息 圖片

看起來是沒吃到\n
你有pull最新的嗎(把\n加回去的)

**Comment by Argentum11** [comment]
> 看起來是沒吃到\n
你有pull最新的嗎(把\n加回去的)

Sorry, it's my fault. All functionalities works now. Thanks for your help

**Pull request merged**
