### PR TITLE
Support negative numbers

### LINKED ISSUE #3: Negative numbers
#2 is unable to support 1 + -1
Fix it in the lex file

### PR DESCRIPTION
**Pull request by Argentum11**
Support 
1. 9+(-2)
2. 3*(-5) and so on
3. 1-1
4. -(-2)

close #3

### CODE REVIEW

**Comment by Argentum11** [comment]
@0-ch Please check if I edit the yacc file correctly. Did I remove the right line that you wrote for support negative numbers in yacc file?

**Comment by 0-ch** [comment]
> @0-ch Please check if I edit the yacc file correctly. Did I remove the right line that you wrote for support negative numbers in yacc file?

-(-2) is error

**Comment by Argentum11** [comment]
> > @0-ch Please check if I edit the yacc file correctly. Did I remove the right line that you wrote for support negative numbers in yacc file?
> 
> -(-2) is error

Ok, it seems like we still need the rule that I deleted. I'll fix it later.

**Comment by 0-ch** [comment]
1-1 is error

**Comment by Argentum11** [comment]
@0-ch  I changed the way for supporting negative numbers. Now you should add parentheses "()" outside of the negative integer. Is this method OK?

**Pull request merged**
