### PR TITLE
Variable arithmetic operations, output stream and endl symbol

### LINKED ISSUE #1: Cout

### LINKED ISSUE #11: Variable math

### PR DESCRIPTION
**Pull request by 0-ch**
## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [x] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Testing**
- [ ] **Other (please describe)**

## Description
1.變數可以當數字用 成為表達式一部分
把輸入1+2 輸出=3 的刪除
把原本輸出變數的刪除 因為變數可以成為表達式(print全刪了)

2.新增輸出串流 cout 和 endl 換行符號
若沒加endl不會自動換行

3.刪除print 因cout做出來了

## Expected behavior
|command name|command example|command output|
|-|-|-|
|變數可以當數字用|x=2;|store x = 2\n|
|變數可以當數字用|x=x+2;|store x = 4\n|
|變數可以當數字用、新增輸出串流 cout 和 endl 換行符號|cout<<x+2<<x<<endl;|64\n|
|cout能不換行|cout<<x;|4|

## Related Issue
close #11 
close #1

### CODE REVIEW

**Review by Argentum11 — CHANGES_REQUESTED** [review]
@0-ch 
1. The commit [9783e11](https://github.com/Argentum11/CFE_for_C/pull/19/commits/9783e11697098d6869e10be62b016a4505815a0f) isn't refactoring, you deleted a existing feature therefore it should be labeled as Breaking change (please fix the pr description)
2. Please update readme about the manual of assigning variables and print variables

**Comment by 0-ch** [comment]
> @0-ch
> 
> 1. The commit [9783e11](https://github.com/Argentum11/CFE_for_C/pull/19/commits/9783e11697098d6869e10be62b016a4505815a0f) isn't refactoring, you deleted a existing feature therefore it should be labeled as Breaking change (please fix the pr description)
> 2. Please update readme about the manual of assigning variables and print variables

小改了code 也改描述了 麻煩再看一遍

**Comment by 0-ch** [comment]
@Argentum11 
做出outpur stream了 把print刪了 描述也有修了 麻煩確認一下
然後下個我可能做輸出string 我想等其他分支合起來再做 
最後整個專案做完的時候 宣告變數的提醒 像store x=2\n這個 要刪掉 小提醒一下

**Comment by Argentum11** [comment]
> @Argentum11 做出outpur stream了 把print刪了 描述也有修了 麻煩確認一下 然後下個我可能做輸出string 我想等其他分支合起來再做 最後整個專案做完的時候 

@0-ch The output stream works, I've fix all the previous test case and add cases for all kinds of cout. Please check if new tests works

> 宣告變數的提醒 像store x=2\n這個 要刪掉 小提醒一下

We need to discuss this next meeting

**Review by Argentum11 — CHANGES_REQUESTED** [review]
Please check if new tests works

**Comment by 0-ch** [comment]
> Please check if new tests works

passed

**Review by Argentum11 — APPROVED** [review]

**Pull request merged**
